from pathlib import Path

# FILES PATH
ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'files'
WINDOW_ICON_PATH = FILES_DIR / 'icon.png'

# SIZING
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 22
SMALL_FONT_SIZE = 16
TEXT_MARGIN = 16
MINIMUM_WIDTH = 300

# COLORS
SPECIAL_PRIMARY_COLOR = '#eb9000'
SPECIAL_DARKER_PRIMARY_COLOR = '#b06c00'
SPECIAL_DARKEST_PRIMARY_COLOR = '#8d5600'

PRIMARY_COLOR = "#666666"
DARKER_PRIMARY_COLOR = "#595959"
DARKEST_PRIMARY_COLOR = "#414141"